#### OpenCV 기본 사용법

In [35]:
import cv2
import os
import numpy as np

In [36]:
# 이미지 관련 공통 변수
IMG_DIR = '../image/'

[1] 이미지 읽기 ==> ndarray


In [37]:
# 이미지 파일 경로 +
IMG_FILE = IMG_DIR+'logo.png'

# 이미지 데이터
im_data = cv2.imread(IMG_FILE)
gray_data = cv2.imread(IMG_FILE, flags=cv2.IMREAD_GRAYSCALE)  # 회색 이미지로 가지고 와라

In [38]:
print(f'shape {im_data.shape}')
print(f'ndim {im_data.ndim}')   # 행과 열이라 세로 가로임 

shape (184, 544, 3)
ndim 3


In [39]:
def printdf(data):
    print(f'[{data}]')
    print(f'shape {data.shape}')
    print(f'ndim {data.ndim}D')

printdf(im_data)
printdf(gray_data)

[[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [255 255   0]
  [255 255   0]
  [255 255   0]]

 [[255 255   0]
  [255 255   0]
  [255 255   0]
  ...
  [255 255   0]
  [255 255   0]
  [255 255   0]]

 [[255 255   0]
  [255 255   0]
  [255 255   0]
  ...
  [243 133  66]
  [243 133  66]
  [243 133  66]]

 ...

 [[233 127  63]
  [233 127  63]
  [233 127  63]
  ...
  [233 127  63]
  [233 127  63]
  [233 127  63]]

 [[233 127  63]
  [233 127  63]
  [233 127  63]
  ...
  [233 127  63]
  [233 127  63]
  [233 127  63]]

 [[233 127  63]
  [233 127  63]
  [233 127  63]
  ...
  [233 127  63]
  [233 127  63]
  [233 127  63]]]]
shape (184, 544, 3)
ndim 3D
[[[  0   0   0 ... 178 178 178]
 [178 178 178 ... 178 178 178]
 [178 178 178 ... 125 125 125]
 ...
 [119 119 119 ... 119 119 119]
 [119 119 119 ... 119 119 119]
 [119 119 119 ... 119 119 119]]]
shape (184, 544)
ndim 2D


In [40]:
# cv2.imshow('[IM_DATA]', im_data)
# cv2.waitKey()

In [41]:
# for _ in range(10):
#     print(cv2.waitKey(1000) )   # ms 마다 기다림

 - [2] 이밎 화면 출력 ==> imshow()


In [42]:
# import time
# #이미지 창 띄우기 
# cv2.imshow("IM_DATA", im_data)
# cv2.imshow("GRAY_DATA", gray_data)



# cv2.waitKey()
# cv2.destroyAllWindows("IM_DATA")
# time.sleep(1)
# cv2.destroyAllWindows("IM_DATA")

###

In [43]:
# .### x, x 업적 시 ㅁ도든 장니ㅣㅇ 니힐,ㄹ ㅇ닐,
# cv2.fluiso
# prunt(*f"ket_code = >graydata
#       llplt.alkl[[]]")

In [45]:
import time
#이미지 창 띄우기 
cv2.imshow("IM_DATA", im_data)
cv2.imshow("GRAY_DATA", gray_data)

while True:

    # 키보드 대기 함수 
    key_code = cv2.waitKey()
    print(f'key_code => {key_code}, {chr(key_code)}')

    if chr(key_code) in ['x','X ']:
        cv2.destroyAllWindows()
    elif chr (key_code) in [s''''StopAsyncIterationcv]
                            
                            

ValueError: chr() arg not in range(0x110000)