In [1]:
import numpy as np
import pandas as pd

### Chap 01

In [3]:
print(np.ndarray)

<class 'numpy.ndarray'>


In [6]:
np.ndarray.__name__

'ndarray'

In [7]:
for i in dir(np.ndarray):
    if not i.startswith("_"):
        if type(np.ndarray.__dict__[i] != type(np.ndarray.var)):
            print(i)

T
all
any
argmax
argmin
argpartition
argsort
astype
base
byteswap
choose
clip
compress
conj
conjugate
copy
ctypes
cumprod
cumsum
data
diagonal
dot
dtype
dump
dumps
fill
flags
flat
flatten
getfield
imag
item
itemset
itemsize
max
mean
min
nbytes
ndim
newbyteorder
nonzero
partition
prod
ptp
put
ravel
real
repeat
reshape
resize
round
searchsorted
setfield
setflags
shape
size
sort
squeeze
std
strides
sum
swapaxes
take
tobytes
tofile
tolist
tostring
trace
transpose
var
view


In [12]:
a = [1,2,3,4]
b = np.array(a)
b, type(b)

(array([1, 2, 3, 4]), numpy.ndarray)

In [15]:
b.data.obj

array([1, 2, 3, 4])

In [17]:
# e = np.array(a,dtype=np.float)
e

NameError: name 'e' is not defined

In [21]:
a2 = np.array([[1,2,3],[4,5,6]])
a2.shape, a2.ndim, a2.dtype, a2.itemsize, a2.size, a2.strides

((2, 3), 2, dtype('int32'), 4, 6, (12, 4))

In [22]:
a = dir(np)
np.ufunc

numpy.ufunc

In [24]:
count = 0
for i in a :
    if i == "Tester" :
        continue
    if type(np.__dict__[i] == np.ufunc):
        print(i, end=" ")
        count += 1
        if count % 5 == 0:
            print()

ALLOW_THREADS BUFSIZE CLIP DataSource ERR_CALL 
ERR_DEFAULT ERR_IGNORE ERR_LOG ERR_PRINT ERR_RAISE 
ERR_WARN FLOATING_POINT_SUPPORT FPE_DIVIDEBYZERO FPE_INVALID FPE_OVERFLOW 
FPE_UNDERFLOW False_ Inf Infinity MAXDIMS 
MAY_SHARE_BOUNDS MAY_SHARE_EXACT NAN NINF NZERO 
NaN PINF PZERO RAISE RankWarning 
SHIFT_DIVIDEBYZERO SHIFT_INVALID SHIFT_OVERFLOW SHIFT_UNDERFLOW ScalarType 
True_ UFUNC_BUFSIZE_DEFAULT UFUNC_PYVALS_NAME WRAP _CopyMode 
_NoValue _UFUNC_API __NUMPY_SETUP__ __all__ __builtins__ 
__cached__ __config__ __deprecated_attrs__ __dir__ __doc__ 
__expired_functions__ __file__ __former_attrs__ __future_scalars__ __getattr__ 
__loader__ __name__ __package__ __path__ __spec__ 
__version__ _add_newdoc_ufunc _builtins _distributor_init _financial_names 
_get_promotion_state _globals _int_extended_msg _mat _no_nep50_warning 
_pyinstaller_hooks_dir _pytesttester _set_promotion_state _specific_msg _typing 
_using_numpy2_behavior _utils abs absolute add 
add_docstring add_newdoc add_newdoc

KeyError: 'testing'

In [26]:
a = np.arange(6,10)
a

array([6, 7, 8, 9])

In [27]:
b = np.arange(10,14)
b

array([10, 11, 12, 13])

In [28]:
c = a * b
c

array([ 60,  77,  96, 117])

In [29]:
a2 = np.array([1,2,3,4])
a2

array([1, 2, 3, 4])

In [30]:
a2 = a2.reshape(2,2)
a2

array([[1, 2],
       [3, 4]])

In [31]:
np.sum(a2), np.sum(a2, axis = 0), np.sum(a2, axis = 1)

(10, array([4, 6]), array([3, 7]))

In [32]:
a = np.array([4,5])
b = np.array([3,4,6])
a.shape, b.shape

((2,), (3,))

In [33]:
try:
    a+b
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (2,) (3,) 


### Chap 02

### Chap 03